version: '2'
services:
    ppoker-app:
        image: ppoker
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ppoker-mysql:3306/ppoker?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ppoker-mysql:
        extends:
            file: mysql.yml
            service: ppoker-mysql
